version: "2"
services:
  web:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ~/.certs:/etc/certs
    ports:
     - "443:443"
    networks:
     - network
  jenkins:
    image: jenkinsci/blueocean
    volumes:
     - ./jenkins-data:/var/jenkins_home:Z
     - /var/run/docker.sock:/var/run/docker.sock:Z
     - ~:/home:Z
    networks:
     - network
networks:
  network:
